parser: '@typescript-eslint/parser'
parserOptions:
  project: "./tsconfig.json"
plugins:
  - '@typescript-eslint'
  - '@typescript-eslint/eslint-plugin'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
rules: {
  no-unused-vars: "off",
  "@typescript-eslint/no-unused-vars": "error",
  "@typescript-eslint/no-namespace": "off"
}
