import { eq, gt, gte, lt, lte } from 'lodash';

export default {
  // comparisonOperators: [
  //     'And',
  //     'BooleanEquals',
  //     'Not',
  //     'NumericEquals',
  //     'NumericGreaterThan',
  //     'NumericGreaterThanEquals',
  //     'NumericLessThan',
  //     'NumericLessThanEquals',
  //     'Or',
  //     'StringEquals',
  //     'StringGreaterThan',
  //     'StringGreaterThanEquals',
  //     'StringLessThan',
  //     'StringLessThanEquals',
  //     'TimestampEquals',
  //     'TimestampGreaterThan',
  //     'TimestampGreaterThanEquals',
  //     'TimestampLessThan',
  //     'TimestampLessThanEquals'
  // ],

  supportedComparisonOperator: [
    'BooleanEquals',
    'NumericEquals',
    'NumericGreaterThan',
    'NumericGreaterThanEquals',
    'NumericLessThan',
    'NumericLessThanEquals',
    'StringEquals',
    'StringGreaterThan',
    'StringGreaterThanEquals',
    'StringLessThan',
    'StringLessThanEquals',
    'TimestampEquals',
    'TimestampGreaterThan',
    'TimestampGreaterThanEquals',
    'TimestampLessThan',
    'TimestampLessThanEquals',
  ],

  convertOperator: {
    BooleanEquals: (value: boolean, other: boolean): boolean => eq(value, other),
    NumericEquals: (value: number, other: number): boolean => eq(value, other),
    NumericGreaterThan: (value: number, other: number): boolean => gt(value, other),
    NumericGreaterThanEquals: (value: number, other: number): boolean => gte(value, other),
    NumericLessThan: (value: number, other: number): boolean => lt(value, other),
    NumericLessThanEquals: (value: number, other: number): boolean => lte(value, other),
    StringEquals: (value: string, other: string): boolean => eq(value, other),
    StringGreaterThan: (value: string, other: string): boolean => gt(value, other),
    StringGreaterThanEquals: (value: string, other: string): boolean => gte(value, other),
    StringLessThan: (value: string, other: string): boolean => lt(value, other),
    StringLessThanEquals: (value: string, other: string): boolean => lte(value, other),
    TimestampEquals: (value: unknown, other: unknown): boolean => eq(value, other),
    TimestampGreaterThan: (value: unknown, other: unknown): boolean => gt(value, other),
    TimestampGreaterThanEquals: (value: unknown, other: unknown): boolean => gte(value, other),
    TimestampLessThan: (value: unknown, other: unknown): boolean => lt(value, other),
    TimestampLessThanEquals: (value: unknown, other: unknown): boolean => lte(value, other),
  },
};
